services:
  investiq-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_RAG=true
    container_name: investiq
    ports:
      - "8080:8000"
    # volumes:
    #   - .:/app  # Disable volume mount in production so the built container code runs
    env_file:
      - .env
    environment:
      # Prevent python from writing pyc files to disc
      - PYTHONDONTWRITEBYTECODE=1
      # Prevent python from buffering stdout and stderr
      - PYTHONUNBUFFERED=1
      # Explicitly declared API keys removed to prevent Synology overwriting them with empty strings from the host
      # The container will securely load them directly from the .env file instead.
    restart: unless-stopped
